MVCProject/Models/Governorate.cs
using System.ComponentModel.DataAnnotations;

namespace MVCProject.Models
{
    //this model craeted br salah & rizk not emplemented

    public class Governorate
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(20, ErrorMessage = "Governorate name must be less than 20 char")]
        [MinLength(3, ErrorMessage = "Governorate name must be more than 3char")]
        public string Name { get; set; }
        public List<Trader> Traders { get; set; }=new List<Trader>();   

        public List<City> Cities { get; set; }=new List<City>();

        public bool IsDeleted { get; set; }
    }
}

MVCProject/Controllers/GovernorateController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVCProject.Models;
using MVCProject.Repository.CityRepo;
using MVCProject.Repository.GovernorateRepo;
using MVCProject.ViewModel;

namespace MVCProject.Controllers
{
    [Authorize(Roles = "Employee, Admin")]
    public class GovernorateController : Controller
    {
        IGovernRepository _governRepository;
        ICityRepository _cityRepository;
        public GovernorateController(IGovernRepository governRepository, ICityRepository cityRepository)
        {
            _governRepository = governRepository;
            _cityRepository = cityRepository;

        }
        public IActionResult Index(string word)
        {
            List<Governorate> governorates;
            if (string.IsNullOrEmpty(word))
            {
                governorates = _governRepository.GetAll();
            }
            else
            {
                governorates = _governRepository.GetAll().Where(
                                e => e.Name.ToLower().Contains(word.ToLower())).ToList();
            }
            return View(governorates);
        }
        public IActionResult Details(int id)
        {
            var cites = _cityRepository.GetAllCitiesByGovId(id);
            ViewData["GovName"] = _governRepository.GetById(id).Name;
            return View(cites);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Governorate governorate)
        {
            if (ModelState.IsValid)
            {

                _governRepository.Add(governorate);
                _governRepository.Save();
                return RedirectToAction("Index");
            }
            return View(governorate);
        }
        public IActionResult Edit(int id)
        {
            Governorate governorate = _governRepository.GetById(id);
            return View(governorate);
        }
        [HttpPost]
        public IActionResult Edit(Governorate governorate)
        {
            if (ModelState.IsValid)
            {
                _governRepository.Edit(governorate);
                _governRepository.Save();
                return RedirectToAction("Index");
            }
            return View(governorate);
        }
        public IActionResult Delete(int id)
        {
            _governRepository.Delete(id);
            _governRepository.Save();
            return Content("sucsses");
        }
    }

}

MVCProject/Views/Governorate/Create.cshtml
@model Governorate
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<form method="post" asp-action="Create">
    @Html.AntiForgeryToken()
@*    <input class="form-control" asp-for="Id" hidden="" />*@
    <div>
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <input type="submit" value="Create" class="btn btn-primary my-3" />
</form>

MVCProject/Views/Governorate/Details.cshtml
@model List<City>
@{
    ViewData["Title"] = "Details";
}

<h1>@ViewBag.GovName</h1>

<table class="table table-bordered table-hover">
    <tr>
        <th>City Name</th>
        <th>Shipping Cost</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name </td>
            <td>@item.ShippingCost</td>
        </tr>
    }
</table>
<a asp-action="Index" class="btn btn-primary"> Back </a>

MVCProject/Views/Governorate/Edit.cshtml
@model Governorate
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<form method="post" asp-action="Edit">
    @Html.AntiForgeryToken()
    <input class="form-control" asp-for="Id" hidden="" />
    <div>
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div>
        <input class="my-3" type="checkbox" asp-for="IsDeleted" />
        <label>Is Not Avilable</label>

    </div>
    <input type="submit" value="Save" class="btn btn-primary"   />
</form>

MVCProject/Views/Governorate/Index.cshtml
@model List<Governorate>
@{
    ViewData["Title"] = "Index";
}

<h1>Governorates</h1>

<a asp-action="Create" class="btn btn-primary mb-3">Add New Governrate</a>

<div class="card shadow mb-4 text-center">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name </th>
                        <th>State</th>
                        <th></th>
                        <th></th>
                        <th></th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="row_@item.Id">
                            <td>@item.Id </td>
                            <td>@item.Name</td>
                            <td>
                                <input class="form-check-input" type="checkbox" role="switch" id="switch-@item.Id" @(item.IsDeleted ? "" : "checked")>
                            </td>
                            <td>
                                <a asp-action="Edit" asp-controller="Governorate" asp-route-id="@item.Id" class="btn btn-outline-primary">Edit</a>

                            </td>
                            <td>
                                <input type="submit" class="btn btn-outline-danger" value="Delete" onclick="Delete(@item.Id)" />
                            </td>
                            <td>
                                <a asp-action="Details" asp-controller="Governorate" asp-route-id="@item.Id" class="btn btn-outline-success">Details</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts
    {
    @*  <script src="~/lib/jquery/dist/jquery.js"></script>*@
    <script>
        function Delete(id) {
            if (confirm(`Are you sure you want delete this item `)) {

                $.ajax({
                    type: "POST",
                    url: `@Url.Action("Delete")`,
                    data: { id: id },
                    dataType: "text",
                    success: function (response) {
                        if (response.trim() == "sucsses") {
                            $("#row_" + id).remove()
                        }
                    },
                    error: function () {
                        alert("Error while deleting data");
                    }
                });
            }

        }
    </script>
}