MVCProject/Models/Branch.cs
using System.ComponentModel.DataAnnotations;

namespace MVCProject.Models
{
    public class Branch
    {
        public int Id { get; set; }

        [MaxLength(50)]
        [MinLength(3, ErrorMessage = "Name must be more than 3 char")]
        public string Name { get; set; }

        public DateTime? CreationDate { get; set; } = DateTime.Now;

        public bool IsDeleted { get; set; } = false;
        public List<Trader>? Traders { get; set; }
        public List<Employee>? Employees { get; set; }
    }
}

MVCProject/Controllers/BranchController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVCProject.Models;
using MVCProject.Repository.BranchRepo;
using MVCProject.Repository.TraderRepo;

namespace MVCProject.Controllers
{
    [Authorize(Roles = "Employee, Admin")]
    public class BranchController : Controller
    {
        IBranchRepository _branchRepository;
        ITraderRepository _traderRepository;

        public BranchController(IBranchRepository branchRepository, ITraderRepository traderRepository)
        {
            _branchRepository = branchRepository;
            _traderRepository = traderRepository;
        }

        public IActionResult Index(string word)
        {
            List<Branch> branches;
            if (string.IsNullOrEmpty(word))
            {
                branches = _branchRepository.GetAll();
            }
            else
            {
                branches = _branchRepository.GetAll().Where(
                                e => e.Name.ToLower().Contains(word.ToLower())).ToList();

            }
            return View(branches);

        }

        public IActionResult Details(int id)
        {
            var traders = _traderRepository.GetAllTradersByBranchId(id);
            ViewData["BranchName"] = _branchRepository.GetById(id).Name;

            return View(traders);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Branch branch)
        {
            if (ModelState.IsValid)
            {
                _branchRepository.Add(branch);
                _branchRepository.Save();
                return RedirectToAction("Index");
            }

            return View(branch);
        }

        public IActionResult Edit(int id)
        {
            Branch branch = _branchRepository.GetById(id);
            return View(branch);
        }
        [HttpPost]
        public IActionResult Edit(Branch branch)
        {

            if (ModelState.IsValid)
            {
                _branchRepository.Edit(branch);
                _branchRepository.Save();
                return RedirectToAction("Index");
            }
            return View(branch);

        }

        public IActionResult Delete(int id)
        {
            _branchRepository.Delete(id);
            _branchRepository.Save();
            return Content("sucsses");
        }
    }
}

MVCProject/Views/Branch/Add.cshtml
@model MVCProject.Models.Branch

@{
    ViewData["Title"] = "Add";
}


<h4>Add Branch</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
 
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCProject/Views/Branch/Details.cshtml
@model List<Trader>

@{
    ViewData["Title"] = "Details";
}
<h1>@ViewBag.BranchName</h1>

<table class="table table-bordered table-hover">
    <tr>
        <th>Trader Name</th>
        <th>Store Name</th>
        <th>Special Pickup Cost</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name </td>
            <td>@item.StoreName</td>
            <td>@item.SpecialPickupCost</td>
        </tr>
    }
</table>
<a asp-action="Index" class="btn btn-primary"> Back </a>

MVCProject/Views/Branch/Edit.cshtml
@model Branch

@{
    ViewData["Title"] = "Edit";
}


<h4>Edit Branch</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            @Html.AntiForgeryToken()
            <input class="form-control" asp-for="Id" hidden="" />
            <div>
                <label asp-for="Name"></label>
                <input class="form-control" asp-for="Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div>
                <label>IsNotAvilable</label>
                <input type="checkbox" asp-for="IsDeleted" />

            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MVCProject/Views/Branch/Index.cshtml
@model List<Branch>

@{
    ViewData["Title"] = "Index";
}
<a asp-action="Add" class="btn btn-primary mb-3">Add New Branch</a>
<div class="card shadow mb-4 text-center">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name </th>
                        <th>CreationDate </th>
                        <th>State</th>
                        <th></th>
                        <th></th>
                        <th></th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="row_@item.Id">
                            <td>@item.Id </td>
                            <td>@item.Name</td>
                            <td>@item.CreationDate</td>
                            <td>
                                <input class="form-check-input" type="checkbox" role="switch" id="switch-@item.Id" @(item.IsDeleted ? "unchecked" : "checked")>
                            </td>
                            <td>
                                <a asp-action="Edit" asp-controller="Branch" asp-route-id="@item.Id" class="btn btn-outline-primary">Edit</a>

                            </td>
                            <td>
                                <input type="submit" class="btn btn-danger" value="Delete" onclick="Delete(@item.Id)" />
                            </td>
                            <td>
                                <a asp-action="Details" asp-controller="Branch" asp-route-id="@item.Id" class="btn btn-outline-success">Details</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


@section Scripts{
    <script>
        function Delete(id) {
            if (confirm(`Are you sure you want delete this item `)) {

                $.ajax({
                    type: "POST",
                    url: `@Url.Action("Delete")`,
                    data: { id: id },
                    dataType: "text",
                    success: function (response) {
                        if (response.trim() == "sucsses") {
                            $("#row_" + id).remove()
                        }
                    },
                    error: function () {
                        alert("Error while deleting data");
                    }
                });
            }

        }
    </script>
}